In [1]:
# tirgul4
# random
import numpy as np
e = np.random.random((2,4)) 
print(e)

[[0.07428974 0.05837925 0.34521664 0.0466583 ]
 [0.94180123 0.80421662 0.38195502 0.79660827]]


In [2]:
numCols = 6
grades = np.random.randint(70,100,size=(10,numCols))
print(grades)

[[82 93 77 71 88 71]
 [93 91 81 97 74 79]
 [78 91 96 72 99 77]
 [94 73 99 94 87 92]
 [91 89 89 90 88 73]
 [91 74 83 93 91 82]
 [86 81 95 98 71 73]
 [71 78 99 94 99 78]
 [81 87 73 84 90 98]
 [96 98 98 96 96 70]]


In [3]:
top5Avg = (grades.sum(axis=1)-grades.min(axis=1)) / (numCols-1)
top5Avg
top5Avg = top5Avg.reshape(len(top5Avg),1) # for display purpose
print(top5Avg)

[[82.2]
 [88.2]
 [88.2]
 [93.2]
 [89.4]
 [88. ]
 [86.6]
 [89.6]
 [88. ]
 [96.8]]


In [4]:
# let's read it using pandas
import pandas as pd
url = 'https://raw.githubusercontent.com/nlihin/data-analytics/main/datasets/italy-covid-daywise.csv'
covid_df = pd.read_csv(url)
covid_df.tail()

date  new_cases  new_deaths  new_tests
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

In [5]:
# let's focus on date column
covid_df["date"]


0      2019-12-31
1      2020-01-01
2      2020-01-02
3      2020-01-03
4      2020-01-04
          ...    
243    2020-08-30
244    2020-08-31
245    2020-09-01
246    2020-09-02
247    2020-09-03
Name: date, Length: 248, dtype: object

In [6]:
# note that date type is object. let's convert it to pandas datetime
# for pandas datetime reference and examples: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html 
# video tutorial: https://www.youtube.com/watch?v=UFuo7EHI8zc
covid_df['date'] = pd.to_datetime(covid_df.date)
covid_df['date']

0     2019-12-31
1     2020-01-01
2     2020-01-02
3     2020-01-03
4     2020-01-04
         ...    
243   2020-08-30
244   2020-08-31
245   2020-09-01
246   2020-09-02
247   2020-09-03
Name: date, Length: 248, dtype: datetime64[ns]

In [7]:
# now we can extract the year,month,day and weekday properties (and muchmore - for ) 
covid_df['year'] = pd.DatetimeIndex(covid_df.date).year
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month
covid_df['day'] = pd.DatetimeIndex(covid_df.date).day
covid_df['weekday'] = pd.DatetimeIndex(covid_df.date).weekday
covid_df

date  new_cases  new_deaths  new_tests  year  month  day  weekday
0   2019-12-31        0.0         0.0        NaN  2019     12   31        1
1   2020-01-01        0.0         0.0        NaN  2020      1    1        2
2   2020-01-02        0.0         0.0        NaN  2020      1    2        3
3   2020-01-03        0.0         0.0        NaN  2020      1    3        4
4   2020-01-04        0.0         0.0        NaN  2020      1    4        5
..         ...        ...         ...        ...   ...    ...  ...      ...
243 2020-08-30     1444.0         1.0    53541.0  2020      8   30        6
244 2020-08-31     1365.0         4.0    42583.0  2020      8   31        0
245 2020-09-01      996.0         6.0    54395.0  2020      9    1        1
246 2020-09-02      975.0         8.0        NaN  2020      9    2        2
247 2020-09-03     1326.0         6.0        NaN  2020      9    3        3

[248 rows x 8 columns]

In [8]:
# now we can present rows of specific dates, for example only August:
# Query the rows for May
covid_df_august = covid_df[covid_df.month == 8]
covid_df_august.head()

date  new_cases  new_deaths  new_tests  year  month  day  weekday
214 2020-08-01      379.0         9.0    31905.0  2020      8    1        5
215 2020-08-02      295.0         5.0    24496.0  2020      8    2        6
216 2020-08-03      238.0         8.0    13467.0  2020      8    3        0
217 2020-08-04      159.0        12.0    23491.0  2020      8    4        1
218 2020-08-05      190.0         5.0    29739.0  2020      8    5        2

In [9]:
# Extract the subset of columns to be aggregated
covid_df_august_metrics = covid_df_august[['new_cases', 'new_deaths', 'new_tests']]

# Get the column-wise sum
covid_august_totals = covid_df_august_metrics.sum()
covid_august_totals

new_cases       21060.0
new_deaths        345.0
new_tests     1098704.0
dtype: float64

In [10]:
# we can do the same for mean 
covid_df_august_metrics.mean()

new_cases       679.354839
new_deaths       11.129032
new_tests     35442.064516
dtype: float64

In [11]:
#or median
covid_df_august_metrics.median()

new_cases       522.0
new_deaths        6.0
new_tests     31905.0
dtype: float64

In [12]:
# use groupby command
# let's sum:
covid_month_df_sum = covid_df.groupby('month')[['new_cases', 'new_deaths', 'new_tests']].sum()
covid_month_df_sum
# deaths per months graphs
# hist cborn

new_cases  new_deaths  new_tests
month                                  
1            3.0         0.0        0.0
2          885.0        21.0        0.0
3       100851.0     11570.0        0.0
4       101852.0     16091.0   419591.0
5        29073.0      5658.0  1078720.0
6         7772.0      1404.0   830354.0
7         6722.0       388.0   797692.0
8        21060.0       345.0  1098704.0
9         3297.0        20.0    54395.0
12           0.0         0.0        0.0

In [13]:
# we could do the same for mean or any other stats
covid_df.groupby('month')[['new_cases', 'new_deaths', 'new_tests']].mean()

new_cases  new_deaths     new_tests
month                                       
1         0.096774    0.000000           NaN
2        30.517241    0.724138           NaN
3      3253.258065  373.225806           NaN
4      3395.066667  536.366667  38144.636364
5       937.838710  182.516129  34797.419355
6       259.066667   46.800000  27678.466667
7       216.838710   12.516129  25732.000000
8       679.354839   11.129032  35442.064516
9      1099.000000    6.666667  54395.000000
12        0.000000    0.000000           NaN

In [14]:
# print todays date in pandas:
import pandas as pd
from datetime import date # get python datetime
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2021-03-17 00:00:00


In [15]:
# self learning:.
# 1. calculate total deaths at May in attached 'italy-covid-daywise.csv' fuke
# 2. python pandas datetime excercises (with solutions): 
# https://www.w3resource.com/python-exercises/pandas/datetime/index.php

In [19]:
# solution 2
import pandas as pd
covid_df = pd.read_csv('italy-covid-daywise.csv')
covid_df['date'] = pd.to_datetime(covid_df.date)
covid_df['month'] = pd.DatetimeIndex(covid_df.date).month
totalDeathsInMay = covid_df[covid_df.month == 5]['new_deaths'].sum()
print('total deaths in May: ',totalDeathsInMay)

total deaths in May:  5658.0
