## Add nice equations using LaTEX syntax in Markdown
### Sphere or Quadratic equations::
$ x^2 + y^2 = z^2 \\$
$ \\ x_1,_2 =  \frac{- b\pm \sqrt{b^2-4ac}}{2a} $

In [29]:
import pandas as pd
data = pd.read_csv('titanic_short.csv')
data[10:19]

pclass  survived   age     sex
10    1st         0  47.0    male
11    1st         1  19.0  female
12    1st         1   NaN  female
13    1st         1   NaN    male
14    1st         0   NaN    male
15    1st         1  50.0  female
16    1st         0  24.0    male
17    1st         0  36.0    male
18    1st         1  37.0    male

In [30]:
# not null
filteredData = data[pd.notnull(data['age'])]
filteredData[10:19]

pclass  survived   age     sex
10    1st         0  47.0    male
11    1st         1  19.0  female
15    1st         1  50.0  female
16    1st         0  24.0    male
17    1st         0  36.0    male
18    1st         1  37.0    male
20    1st         1  26.0    male
21    1st         0  25.0    male
23    1st         1  19.0  female

In [4]:
# Mean
dataAge = data['age']
dataAge.mean()


34.90942173913044

In [5]:
dataAge.min()

0.9167

In [6]:
dataAge.max()

71.0

In [7]:
dataAge.median()

30.0

In [ ]:
## Numpy
Matrices and much more, this is where the fun begins..

[Numpy official docs](https://numpy.org/doc/stable/reference/index.html)

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr*arr)

In [ ]:
#### vector multiplication (AKA dot producdt)
print("arr.dot(arr)\t=",arr.dot(arr))
# or by 
print("arr@arr\t\t=",arr@arr)


In [ ]:
# create ones matrix of specific size:
np.ones((2,3))

In [ ]:
# self excercise: create zeros matrix of specific size:






In [ ]:
np.zeros((2,3))

In [ ]:
# The I matrix
d = np.eye(3)
print(d)

In [ ]:
# self excercise: create the following 3X3 diagonal matrix
[1., 0., 0.],
[0., 2., 0.],
[0., 0., 3.]









In [33]:
[1,2,3]*np.eye(3)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [34]:
# random
e = np.random.random((2,4)) 
print(e)

[[0.02945835 0.12904749 0.15490786 0.85034983]
 [0.70968749 0.18958819 0.84031437 0.89609826]]


In [8]:
# append
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([11, 12, 13, 14, 15])
arr3 = np.append(arr1,arr2)
print(arr3)


[ 1  2  3  4  5 11 12 13 14 15]


In [9]:
# we can add arrays of same length
print(arr1+arr2)

[12 14 16 18 20]


In [31]:
# However arrays must have same length
arr3 = np.array([1,2])
print(arr1+arr3) # ERROR

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

In [12]:
# self excercise: Assume hypothethical case where you wish for each student to calculate average of the highest 5 grades out of 6 student's assignment
# step 1. generate 10X6 random integer numbers between 70 to 100 to represent students grades
# step 2. calculate mean of top 5 grades for each student








[[76 86 84 91 74 84]
 [81 95 98 80 71 93]
 [94 87 97 79 96 74]
 [87 76 76 84 87 70]
 [99 82 87 74 83 99]
 [91 70 99 73 76 77]
 [94 73 94 77 76 89]
 [82 82 79 84 87 99]
 [99 82 90 82 97 92]
 [87 85 74 99 98 98]]


In [ ]:
numCols = 6
grades = np.random.randint(70,100,size=(10,numCols))
print(grades)

In [19]:
top5Avg = (grades.sum(axis=1)-grades.min(axis=1)) / (numCols-1)
top5Avg = top5Avg.reshape(len(top5Avg),1)
print(top5Avg)

[[84.2]
 [89.4]
 [90.6]
 [82. ]
 [90. ]
 [83.2]
 [86. ]
 [86.8]
 [92. ]
 [93.4]]
